# Change these first
owner: SOPORTEAYIGROUP # Your GitHub organization or username, where this repository lives
repo: STATUSVEDI # The name of this repository

sites:
  - name: VEDI PROD
    url: https://vedi.cordoba.gob.ar/
  - name: VEDI STAGE
    url: https://vedi.stage.cordoba.gob.ar/
  - name: VEDI TEST
    url: https://vedi.test.cordoba.gob.ar/
 
    
assignees:
  - SOPORTEAYIGROUP

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /STATUSVEDI
  logoUrl: https://vedi.cordoba.gob.ar/VeDiPortal/static/media/vediDrawer.27e91504.png
  name: Status STATUSVEDI
  introTitle: "**STATUS STATUSVEDI** Monitor de uptime y status page."
  introMessage: En caso de caida o degradación de servicio informara automaticamente a Soporte VEDI
  navbar:
    - title: Status
      href: https://soporteayigroup.github.io/STATUSVEDI/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
